Feat/set up enumNames on schema and add pt/en translations
vtex-apps/slider-layout pull request #112
Opened 2023-05-23 20:19 UTC by natanfernandes

#### What problem is this solving?

Add translations for the dropdown options for the props `showNavigationArrows` and `showPaginationDots`

#### How to test it?

* Switch to this branch and link to workspace
* Go to https://{workspace}--{account}.myvtex.com/admin/cms/site-editor -> Image List -> Slider Layout
* Check if the options the `Show navigation arrows` and `Show pagination dots` dropdowns are correctly translated

[Workspace](https://natandevuamerge--storecomponents.myvtex.com/admin/cms/site-editor)

#### Screenshots or example usage:

![Captura de Tela 2023-05-23 às 17 09 02](https://github.com/vtex-apps/slider-layout/assets/36740164/b72f358f-19d2-4035-a823-1355684fa45f)

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/XK7VBhOwU9FlrcZQZg/giphy.gif)

2023-05-24 14:36 UTC, filipewl approved these changes
Looks good to me!

2023-05-24 14:36 UTC, filipewl commented on CHANGELOG.md
> +### Addedd
```suggestion
### Added
```

2023-06-09 12:10 UTC, camilavcoutinho requested changes

2023-06-09 12:10 UTC, camilavcoutinho commented on CHANGELOG.md
> +
```suggestion
- Translations for Bulgarian, German, Spanish, French, Italian, Korean, Dutch, Portuguese, Romanian and Thai.

```

2023-06-09 12:24 UTC, camilavcoutinho approved these changes

2024-08-14 16:43 UTC, iago1501 approved these changes

2024-08-21 14:48 UTC, merged