feat(slider): changed the properties that were generating an error in…
vtex-apps/slider-layout pull request #115
Opened 2023-09-30 15:21 UTC by joaocongio

#### What problem is this solving?

- O atributo aria-controls não possui valor válido, impedindo que leitores de tela consiga interpretar seu valor.
- Os elementos Dots possuem tabIndex maior que 0.  Uma das soluções é manter o tabIndex dos Dots em 0, conforme essa PR.

Esses problemas são acusados na métrica de Acessibilidade pelo Lighthouse.

#### How to test it?

[Workspace](https://www.samsclub.com.br/?workspace=testeapps)
Realizar o teste via Lighthouse ou Pagespeeds e comparar WS com a URL de produção.

#### Screenshots or example usage:

Antes (era acusado pelo Lighthouse):
![image](https://github.com/vtex-apps/slider-layout/assets/22462037/8fcc42a4-2df8-46e5-b3fb-d9fe3a6e727b)
![image](https://github.com/vtex-apps/slider-layout/assets/22462037/7fcb78f1-1dd0-4c7b-b61b-021e1c38e151)

Depois (deixou de ser acusado pelo Lighthouse):
![image](https://github.com/vtex-apps/slider-layout/assets/22462037/6665daea-0bf0-40e6-8cca-a8b4a122d504)

2023-09-30 15:24 UTC, joaocongio commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2023-10-17 11:48 UTC, ganobrega approved these changes
LGTM!

2023-10-31 18:28 UTC, filipewl requested changes
Opa João! Muito obrigado pela primeira contribuição.
🙌 

Analisei o PR e apesar de, aparentemente, ele resolver o problema, acredito que não deva ser desse jeito. Explico: analisei esse componente e de fato, do jeito que está atualmente, ele está reclamando que o atributo `aria-controls` está sendo usado incorretamente. Porém, isso só acontece porque está faltando associar os valores do `aria-controls` (`"slider-items"` por padrão) a um `id` correspondente com este mesmo valor (referencia [1](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls#:~:text=The%20button%20parts%20of%20an%20accordion%20widget%20that%20toggle%20the%20visibility%20of%20their%20associated%20panel%20content.%20Each%20button%20may%20have%20an%20aria%2Dcontrols%20specified%2C%20referencing%20the%20ID%20of%20the%20element%20containing%20the%20content%20associated%20with%20the%20invoking%20control.) e [2](https://w3c.github.io/aria/#aria-controls:~:text=Value%3A-,ID%20reference%20list,-aria%2Dcurrent%20state)). 

Me parece que a solução então é adicionar o attribute `id` num dos elementos wrapper principais do componente com o mesmo valor do `controls`. Acho que adicionar nesse `section` do componente `Slider` resolveria esse caso. Faz sentido?
![CleanShot 2023-10-31 at 15 27 07](https://github.com/vtex-apps/slider-layout/assets/381395/00e9631e-6caf-420a-8222-3012b3fc6dc9)

Você poderia testar dessa maneira?

https://github.com/vtex-apps/slider-layout/blob/3f56ff452f619b575406278cc052bd3056ba368e/react/components/Slider.tsx#L67-L70

https://github.com/vtex-apps/slider-layout/blob/3f56ff452f619b575406278cc052bd3056ba368e/react/components/Slider.tsx#L96

2023-11-01 00:22 UTC, filipewl commented
Fala @joaocongio! Vi agora seu último commit https://github.com/vtex-apps/slider-layout/pull/115/commits/544a18141dcacea79c1b2cbfdf5159da16400198, mas acredito que ainda não seja isso.

Minha proposta não é remover totalmente as props `controls` usadas nos atributos `aria-controls`, mas sim deixar como eles estão e adicionar um `id` ao `section` do `Slider` com o valor do `controls`. Desta maneira, tanto os botões de anterior/próximo, como os dots, estariam corretamente associados a `section` pelo valor do `id`/`aria-controls`. Isso deve ser suficiente pra resolver [o erro de acessibilidade reportado](https://dequeuniversity.com/rules/axe/4.7/aria-valid-attr-value).

2023-11-01 17:56 UTC, joaocongio commented
> Fala @joaocongio! Vi agora seu último commit [544a181](https://github.com/vtex-apps/slider-layout/commit/544a18141dcacea79c1b2cbfdf5159da16400198), mas acredito que ainda não seja isso.
> 
> Minha proposta não é remover totalmente as props `controls` usadas nos atributos `aria-controls`, mas sim deixar como eles estão e adicionar um `id` ao `section` do `Slider` com o valor do `controls`. Desta maneira, tanto os botões de anterior/próximo, como os dots, estariam corretamente associados a `section` pelo valor do `id`/`aria-controls`. Isso deve ser suficiente pra resolver [o erro de acessibilidade reportado](https://dequeuniversity.com/rules/axe/4.7/aria-valid-attr-value).

Desculpa, acabei vendo apenas um comentário.
Analisei o que você comentou e faz sentido sim, associar a section, arrow e dots à um ID. Utilizando essa estratégia, o Lighthouse também deixou de acusar o problema.
Nesse último commit eu voltei os controls e associei o id da section a arrow e dots.
Para a propriedade ID mantive o padrão "slider-items", porém adicionei também um identificador randômico para não ter duplicações de ID. Possui alguma ideia diferente ou que possa ser melhor?
Para os dots, alterei a estratégia do tabIndex, antes eu havia deixado todos com o valor 0. Agora apenas o dot ativo fica com o valor 0 e o restante que não está em tela, fica com -1. [Ref TabIndex](https://dequeuniversity.com/rules/axe/4.7/tabindex).

2023-11-06 20:07 UTC, filipewl approved these changes
Muito obrigado pela contribuição e pela paciência João! 

Farei o merge deste PR e você já poderá instalar manualmente a versão nova que será gerada nas contas que quiser.

Em algum momento posterior, quando as condições foram propícias, nós faremos o deploy geral automático para as demais contas.

2023-11-06 20:10 UTC, merged