New Crowdin updates
vtex-apps/slider-layout pull request #67
Opened 2021-06-18 13:11 UTC by camilavcoutinho

2021-08-13 13:35 UTC, igorbrasileiro reviewed
@camilavcoutinho can you share a workspace link? I don't have enough context about it.

2021-08-13 13:37 UTC, camilavcoutinho commented
> @camilavcoutinho can you share a workspace link? I don't have enough context about it.

2021-08-13 13:38 UTC, camilavcoutinho commented
Hey @igorbrasileiro ! It will only appear when we enable the pseudo language with a script, so don't worry, it will not appear on the UI. The workspace is this one: https://acholi--storecomponents.myvtex.com/admin, but you probably won't have access, because it is linked with Crowdin platform.

2021-09-21 15:32 UTC, daniserejo requested changes

2021-09-21 15:32 UTC, daniserejo commented on CHANGELOG.md
> +- I18n Bg and Ds (pseudo-language to implement in-context tool).
```suggestion
- I18n Bg and Bs (pseudo-language to implement in-context tool).
```

2021-09-21 15:34 UTC, daniserejo approved these changes

2021-09-21 16:27 UTC, camilavcoutinho reviewed
@daniserejo, please remove pt-BR file.

2021-09-21 16:27 UTC, camilavcoutinho commented on CHANGELOG.md
> +
```suggestion

### Fixed
- I18n Es and It.

```

2021-09-24 17:17 UTC, victorhmp approved these changes

2021-09-24 17:17 UTC, merged