adding autoplay to siteditor properties
vtex-apps/slider-layout pull request #80
Opened 2021-11-05 15:14 UTC by julikroch

#### What problem is this solving?

Adding autoplay properties so it can be changed for the sliders from VTEX site editor without code development.

#### How to test it?

https://julianslider--pivotree.myvtex.com/

#### Screenshots or example usage:

![schema](https://user-images.githubusercontent.com/69015833/140533333-e7addf8d-9ae3-40d3-b44a-281876fd0ce0.png)

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2021-11-05 15:54 UTC, julikroch commented
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [ ]  There's nothing new to document 🤔
> [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> [ ]  I just updated 🎉🎉

2021-11-05 15:56 UTC, julikroch commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [ ]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞



> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

2021-11-05 15:57 UTC, julikroch commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [ ]  Patch (backwards-compatible bug fixes)
> * [x]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2021-11-24 16:47 UTC, camilavcoutinho requested changes

2021-11-24 16:47 UTC, camilavcoutinho commented on messages/pt.json
> +  "admin/editor.slider-layout.timeout": "Autoplay's Timeout"
```suggestion
  "admin/editor.slider-layout.autoplay": "Reproduzir automaticamente",
  "admin/editor.slider-layout.stopOnHover": "Parar reprodução automática ao passar o cursor",
  "admin/editor.slider-layout.timeout": "Duração da reprodução automática"
```

2021-11-24 23:01 UTC, julikroch commented
@camilavcoutinho all your changes were approved. Thank you! :)

2021-11-25 11:36 UTC, camilavcoutinho approved these changes

2024-08-26 17:46 UTC, closed without merging